DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
  favourite_id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
  geoname_id INTEGER NOT NULL,
  display_name VARCHAR (255),
  city_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);
